import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import 'leaflet/dist/leaflet.css'
import 'alk-rounded-mtav-med/css/alk-rounded-mtav-med.min.css'
import 'keen-slider/keen-slider.min.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{fontFamily: "ALK Rounded Mtav Med, sans-serif"}}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
